# Generated by Django 5.1.6 on 2025-02-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
