# Generated by Django 5.1.6 on 2025-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_pictures/blank_cover.png', null=True, upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/blank_profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
